September 13, 2024 at 00:51
Welcome to ChickenSnake, for fast custom playtest cards!
[User input]: y

Extracting card data from input file...
No warnings about imported card data to report!

Initializing image creation assets...
To-be-generated file .\DoD3\Playtest_Base_Images\normal_l_w_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_w_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_l_u_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_u_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_l_b_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_b_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_l_r_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_r_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_l_g_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_g_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_r_w_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_w_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_r_u_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_u_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_r_b_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_b_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_r_r_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_r_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\normal_r_g_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\normal_g_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_l_w_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_w_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_l_u_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_u_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_l_b_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_b_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_l_r_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_r_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_l_g_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_g_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_r_w_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_w_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_r_u_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_u_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_r_b_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_b_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_r_r_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_r_base.png
To-be-generated file .\DoD3\Playtest_Base_Images\enchantment_r_g_base.png doesn't exist. Generating...
Accessing base file .\DoD3\Playtest_Base_Images\enchantment_g_base.png

Generating card images...
Finished card 1/340
Finished card 26/340
There was an issue with Geist-Grove
'enchantment_l_m'
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 202, in generate_card_images
    card_image_total.alpha_composite(image_assets[border_info.file_prefix])
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'enchantment_l_m'


Finished card 51/340
Finished card 76/340
Finished card 101/340
There was an issue with Relentless Fortification
'normal_c'
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 202, in generate_card_images
    card_image_total.alpha_composite(image_assets[border_info.file_prefix])
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'normal_c'


Finished card 126/340
Finished card 151/340
Finished card 176/340
There was an issue with Scatterbomb
'normal_l_m'
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 202, in generate_card_images
    card_image_total.alpha_composite(image_assets[border_info.file_prefix])
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'normal_l_m'


There was an issue with Hit the Ground Running
There was an issue saving the image for: Hit the Ground Running
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 287, in generate_card_images
    rgb_image.save(images_save_filepath + f"{card_data.name}.{CARD_PICTURE_FILE_FORMAT}", quality=100)
  File "C:\Python311\Lib\site-packages\PIL\Image.py", line 2568, in save
    save_handler(self, fp, filename)
  File "C:\Python311\Lib\site-packages\PIL\JpegImagePlugin.py", line 813, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0) + im.size, 0, rawmode)], bufsize)
  File "C:\Python311\Lib\site-packages\PIL\ImageFile.py", line 549, in _save
    _encode_tile(im, fp, tile, bufsize, fh)
  File "C:\Python311\Lib\site-packages\PIL\ImageFile.py", line 576, in _encode_tile
    errcode = encoder.encode_to_file(fh, bufsize)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 289, in generate_card_images
    raise ValueError(f"There was an issue saving the image for: {card_data.name}")
ValueError: There was an issue saving the image for: Hit the Ground Running


There was an issue with Shroom Gator Randy
'normal_l_m'
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 202, in generate_card_images
    card_image_total.alpha_composite(image_assets[border_info.file_prefix])
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'normal_l_m'


There was an issue with Reoccuring Bullying
'normal_c'
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 202, in generate_card_images
    card_image_total.alpha_composite(image_assets[border_info.file_prefix])
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'normal_c'


There was an issue with Turn Brave
'normal_c'
Traceback (most recent call last):
  File "C:\Users\Roey Shapiro\Documents\AAB Backup\Programming\MtG\CardData.py", line 202, in generate_card_images
    card_image_total.alpha_composite(image_assets[border_info.file_prefix])
                                     ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'normal_c'


